Repository trezy-studios/js13k-2020, pull requests merged in 2020-08, with the labels that each got.

#5 Add examples for using state
  src/helpers/updateTile.js
  src/index.js
  src/state.js
Labels: ✨ feature

#4 Remove extra builds
  rollup.config.js
Labels: 🤖 devops

#7 HTML injection
  .gitignore
  package.json
  rollup.config.js
  src/helpers/updateTile.js
  src/index.html
  yarn.lock
Labels: 🤖 devops

#10 Add base CSS
  .editorconfig
  package.json
  rollup-plugins/generateHTML.js
  rollup.config.js
  src/index.css
  src/index.html
  src/index.js
  stats.html
  yarn.lock
Labels: ✨ feature, 🤖 devops

#13 Switch to Webpack
  package.json
  rollup-plugins/generateHTML.js
  rollup.config.js
  scripts/postbuild.js
  webpack.config.js
  yarn.lock
Labels: 🤖 devops

#14 Render the UI
  package.json
  src/assets/images/awkward.font.png
  src/assets/images/border.dark.png
  src/assets/images/border.light.png
  src/assets/images/brand.png
  src/assets/images/button.green.png
  src/assets/images/button.purple.png
  src/assets/images/font.png
  src/assets/images/header-border.png
  src/assets/images/thaleah.font.png
  src/assets/images/timer-border.png
  src/assets/images/wall.png
  src/fonts/awkward.js
  src/fonts/thaleah.js
  src/helpers/settings.js
  src/index.css
  src/index.html
  src/index.js
  src/index.scss
  src/maps/test.js
  src/render/canvas.js
  src/render/font.js
  src/structures/Screen.js
  webpack.config.js
  yarn.lock
Labels: ✨ feature

#16 Implement settings
  src/assets/images/border.dark.png
  src/assets/images/border.light.png
  src/assets/images/button.green.png
  src/assets/images/button.purple.png
  src/helpers/settings.js
  src/helpers/updateGameScale.js
  src/index.html
  src/index.js
  src/index.scss
  src/render/canvas.js
  src/render/font.js
Labels: ✨ feature

#15 tile map rendering & tmx import.
  maps/Test.tmx
  package.json
  src/data/grid.js
  src/data/tiles.js
  src/helpers/tileColors.js
  src/index.js
  src/maps/map.js
  src/maps/test.js
  src/render/canvas.js
  webpack.config.js
  yarn.lock
Labels: ℹ help wanted, ✨ feature, 🐛 bug, 💬 question

#22 Add controls
  src/assets/images/spritesheet.png
  src/data/grid.js
  src/data/state.js
  src/data/tiles.js
  src/helpers/decodeTile.js
  src/helpers/spritesheet.js
  src/index.html
  src/index.js
  src/index.scss
  src/maps/map.js
  src/maps/test.js
  src/render/canvas.js
  src/structures/Controller.js
  src/structures/Screen.js
Labels: ✨ feature
